/* Generated By:JavaCC: Do not edit this line. javaccConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface javaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int WHILE = 2;
  /** RegularExpression Id. */
  int FOR = 3;
  /** RegularExpression Id. */
  int SAYI = 4;
  /** RegularExpression Id. */
  int KHARF = 5;
  /** RegularExpression Id. */
  int BHARF = 6;
  /** RegularExpression Id. */
  int ALTTIRE = 7;
  /** RegularExpression Id. */
  int EKSI = 8;
  /** RegularExpression Id. */
  int URL = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int DOUBLE = 11;
  /** RegularExpression Id. */
  int HATA = 12;
  /** RegularExpression Id. */
  int MAIL = 13;
  /** RegularExpression Id. */
  int DEGISKEN = 14;
  /** RegularExpression Id. */
  int YORUM = 15;
  /** RegularExpression Id. */
  int YORUMLAR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"while\"",
    "\"for\"",
    "<SAYI>",
    "<KHARF>",
    "<BHARF>",
    "\"_\"",
    "\"-\"",
    "<URL>",
    "<INTEGER>",
    "<DOUBLE>",
    "<HATA>",
    "<MAIL>",
    "<DEGISKEN>",
    "<YORUM>",
    "<YORUMLAR>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
